"""Initial migration

Revision ID: 202ef9419527
Revises: 
Create Date: 2025-04-20 12:55:39.044218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202ef9419527'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.String(length=200), nullable=True),
    sa.Column('doc_content', sa.String(length=1000), nullable=True),
    sa.Column('doc_type_id', sa.Integer(), nullable=True),
    sa.Column('doc_format', sa.String(length=1000), nullable=True),
    sa.Column('doc_insert_date', sa.DateTime(), nullable=True),
    sa.Column('doc_updated_date', sa.DateTime(), nullable=True),
    sa.Column('doc_file_full_path', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['doc_type_id'], ['doc_type.id'], ),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('doc_type')
    # ### end Alembic commands ###
