"""max caractere change again again again

Revision ID: 9079ac1799d6
Revises: c61c08b55af1
Create Date: 2025-04-21 11:36:07.742183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9079ac1799d6'
down_revision: Union[str, None] = 'c61c08b55af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'doc_content',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=90000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'doc_content',
               existing_type=sa.String(length=90000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###
