"""remove description to doc_type

Revision ID: ecac924ca387
Revises: 5287083e0540
Create Date: 2025-04-20 17:55:28.930502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecac924ca387'
down_revision: Union[str, None] = '5287083e0540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_type', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_type', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
